<a href="https://colab.research.google.com/github/DavoodSZ1993/Dive-into-Deep-Learning-Notes-/blob/main/07_CNN_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Notes

* `torch.t(input)`: Expects input to be <= 2D tensor and transposes dimensions 0, 1.

In [2]:
import torch

A = torch.tensor([[1.0, 2.0],
                  [3.0, 4.0]])

A, A.t()

(tensor([[1., 2.],
         [3., 4.]]), tensor([[1., 3.],
         [2., 4.]]))

### Convolution Layers 

* Class `nn.Conv2d(in_channels, out_channels, kernel_size, bias=True)`: Applies a 2D convolution over an input signal composed of several input planes.
* `in_channels`: Number of channels in the input image
* `out_channels`: Number pf channels produced by the convolution operator.
* `kernel_size`: Size of the convolution kernel.
* `bias=True`: If `True`, adds a learnable bias to the output.

When isntantiate from the `nn.Conv2d()` class, the images applied to this kind of layer should have the format $(N, C_{in}, H, W)$ where:

* $N$ is batch size.
* $C_{in}$ denotes number of channels.
* $H$ is the height in pixels.
* $W$ is the width in pixels.

And output will be of the size $(N, C_{out}, H_{out}, W_{out})$.

In [5]:
X = torch.ones((6, 8))
X[:, 2:6] = 0

Y = torch.zeros((6, 7))
Y[:, 1] = 1
Y[:, 5] = -1

X, Y

(tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
         [1., 1., 0., 0., 0., 0., 1., 1.],
         [1., 1., 0., 0., 0., 0., 1., 1.],
         [1., 1., 0., 0., 0., 0., 1., 1.],
         [1., 1., 0., 0., 0., 0., 1., 1.],
         [1., 1., 0., 0., 0., 0., 1., 1.]]),
 tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
         [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
         [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
         [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
         [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
         [ 0.,  1.,  0.,  0.,  0., -1.,  0.]]))

In [11]:
X = X.reshape((1, 1, 6, 8))

In [13]:
from torch import nn

conv2d = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=(1, 2), bias=False)

Y = conv2d(X)

Y, Y.shape

(tensor([[[[0.7115, 0.5148, 0.0000, 0.0000, 0.0000, 0.1967, 0.7115],
           [0.7115, 0.5148, 0.0000, 0.0000, 0.0000, 0.1967, 0.7115],
           [0.7115, 0.5148, 0.0000, 0.0000, 0.0000, 0.1967, 0.7115],
           [0.7115, 0.5148, 0.0000, 0.0000, 0.0000, 0.1967, 0.7115],
           [0.7115, 0.5148, 0.0000, 0.0000, 0.0000, 0.1967, 0.7115],
           [0.7115, 0.5148, 0.0000, 0.0000, 0.0000, 0.1967, 0.7115]]]],
        grad_fn=<ConvolutionBackward0>), torch.Size([1, 1, 6, 7]))

* Class `nn.LazyConv2d()`: A `torch.nn.Conv2d` module with lazy initialization of the `in_channels` argument of the `Conv2d`

## General Notes