<a href="https://colab.research.google.com/github/DavoodSZ1993/Dive-into-Deep-Learning-Notes-/blob/main/11_3_attention_scoring_functions_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install d2l==1.0.0-alpha1.post0 --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.0/93.0 KB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.0/121.0 KB 5.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.6/83.6 KB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 28.2 MB/s eta 0:00:00


## 11.3 Attention Scoring Functions

### 11.3.2 Convenience Functions

#### Masked Softmax Operation

* `tensor.size(dim=None)`: Returns the size of the given tensor.

In [4]:
import torch
X = torch.tensor([[1, 2],
                  [3, 4]])

X.size(), X.size(dim=0), X.size(dim=1)

(torch.Size([2, 2]), 2, 2)

* `torch.nn.functional.softmax(input, dim=None)`: Applies a softmax function.

In [8]:
X = torch.rand(2, 2)
Y = torch.nn.functional.softmax(X)
Y

<ipython-input-8-829a4aae16de>:2: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  Y = torch.nn.functional.softmax(X)


tensor([[0.3722, 0.6278],
        [0.5094, 0.4906]])

In [10]:
Y = torch.nn.functional.softmax(X, dim=0)
Y

tensor([[0.3963, 0.5347],
        [0.6037, 0.4653]])

* `torch.repeat_interleave(input, repeats)`: Repeat elements of a tensor.

In [12]:
X = torch.tensor([[1, 2], 
                  [3, 4]])
Y = X.repeat_interleave(2)
Y

tensor([1, 1, 2, 2, 3, 3, 4, 4])

In [14]:
Y = X.repeat_interleave(2, dim=1)
Y

tensor([[1, 1, 2, 2],
        [3, 3, 4, 4]])