<a href="https://colab.research.google.com/github/DavoodSZ1993/Dive-into-Deep-Learning-Notes-/blob/main/12_10_adam_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install d2l==1.0.0-alpha1.post0 --quiet

## 12.10 Adam

* Class `torch.optim.Adam(params, lr=0.001, betas=(0.9, 0.999)`: Implements Adam algorithm.
* ** params(iterable)**: iterable of parameters to optimize or dict defining parameter groups.
* **lr(float, optional)**: learning rate (default: 1e-3).
* **betas (Tuple[float, float], optional)**: Coefficients used for computing running averages of gradients and its square (default: (0.9, 0.999)).

* `torch.square(input)`: Returns a new tensor with the square of the elements of the `input`.

In [2]:
import torch

A = torch.randn(4)
B = torch.square(A)
A, B

(tensor([ 0.3254, -0.4503, -0.5704, -0.0145]),
 tensor([1.0589e-01, 2.0279e-01, 3.2533e-01, 2.1080e-04]))

* `torch.sqrt(input)`: Returns a new tensor with the square-root of the elements of `input`.

In [3]:
A = torch.randn(4)
B = torch.sqrt(A)
A, B

(tensor([ 0.2337,  0.4840, -0.2434, -0.1499]),
 tensor([0.4834, 0.6957,    nan,    nan]))

* `torch.sign(input)`: Returns a new tensor with the signs of the elements of `input`.

In [4]:
A = torch.randn(4)
B = torch.sign(A)
A, B

(tensor([ 1.1489,  1.3494, -0.0415, -0.4984]), tensor([ 1.,  1., -1., -1.]))