<a href="https://colab.research.google.com/github/DavoodSZ1993/Dive-into-Deep-Learning-Notes-/blob/main/12_5_minibatch_stochastic_gradient_descent_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install d2l==1.0.0-alpha1.post0 --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.0/93.0 kB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.2/121.2 kB 7.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.9/84.9 kB 4.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 25.6 MB/s eta 0:00:00


## 12.5 Minibatch Stochastic Gradient Descent

### 12.5.1 Vectorization and Caches

* `torch.dot(input, other)`: Computes the dot product of two 1D tensors.

In [2]:
import torch

A = torch.tensor([2, 3])
B = torch.tensor([2, 1])
C = torch.dot(A, B)
C

tensor(7)

* `torch.mv(input, vec)`: Performs a matrix-vector product of the matrix `input` and the vector `vec`.
* If `input` is a ($n \times m$) tensor, `vec` is a 1-D tensor of size $m$, 'out' will be 1-D of size $n$.

In [3]:
A = torch.randn(2, 3) # n x m
B = torch.randn(3)    # m
C = torch.mv(A, B)
C

tensor([-1.4448, -2.4171])

* `torch.mm(input, mat)`: Performs a matrix multiplication of the matrices `input` and `mat`.
* If `input` is a $(n \times m)$ tensor, `mat` is a $(m \times p)$ tensor, `out` will be a $(n \times p)$ tensor.

In [4]:
A = torch.randn(2, 3) # n x m
B = torch.randn(3, 3)    # m x p
C = torch.mm(A, B)
C

tensor([[-2.4065,  1.6474,  3.8753],
        [-5.7819, -0.4093,  5.0291]])

### 12.5.3 Reading the Dataset

* `torch.from_numpy(ndarray)`: Creates a Tensor from a Numpy ndarray.

In [7]:
import numpy as np

A = np.array([1, 2, 3])
B = torch.from_numpy(A)
B, type(B)

(tensor([1, 2, 3]), torch.Tensor)