<a href="https://colab.research.google.com/github/DavoodSZ1993/Dive-into-Deep-Learning-Notes-/blob/main/5_mlp_kaggle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## `os` Built-in Module

This module provides a portable way of using **operating system** dependent functionality.

* `os.mkdir()`: Can be used to create a directory named path with the specific numeric mode.
* `os.path.join()`: Join one or more path components intelligently.
* `os.path.exists()`: Check whether the specific path exists or not.
* `os.path.dirname()`: Used to get the dictionary name from the specific path.
* `os.path.splittext()`: Used to split the pathname into a pair root and ext.

## `tarfile` Module

We can create tar files using this module. This module makes it possible to read and write tar archives, including those using gzip, bz2 and lzma compression.

* `tarfile.open()`: Return a tarfile object.

## `zipfile` Module

This module provides tools to create, read, write, append, and list ZIP files.

* `zipfile.ZipFile()`: Open a ZIP file.

## With Open in Python

* `open()`: This function opens a file in python. However, the `open()` function does not close the file. So, the file should be closed with `close()` method. 
* The `with` statement works with the `open()` function to open a file.
* Unlike the `open()` where we have to close the file with the `close()` method, the `with` statement closes the file authomatically.

## Preprocessing the Data
### `opendatasets`
`opendatasets` is a Python library for downloading datasets from online sources like Kaggle and Google Drive using a simple Python command.

In [1]:
!pip install opendatasets --upgrade --quiet

In [2]:
import opendatasets as od

dataset_url = 'https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/data'
od.download(dataset_url)

Skipping, found downloaded files in "./house-prices-advanced-regression-techniques" (use force=True to force download)


In [3]:
import pandas as pd

df_train = pd.read_csv('./house-prices-advanced-regression-techniques/train.csv')
df_val = pd.read_csv('./house-prices-advanced-regression-techniques/test.csv')

df_train.shape, df_val.shape

((1460, 81), (1459, 80))

* `pd.concat()`: Concatenate pandas objects along a particular axis.
* `df.dtypes()`: Return the dtypes in the DataFrame.
* `df.apply()`: Apply a function along an axis of the DataFrame.
* `df.fillna()`: Fill NA/NaN values using the specified method.
* `pd.get_dummies()`: Convert categorical variable into dummy/indicator variables. 
* `df.index`: The index (raw label) of the DataFrame.

In [4]:
# Removing index and label columns

label = 'SalePrice'

raw_train = df_train.drop(columns=['Id', label])
raw_val = df_val.drop(columns = ['Id'])

raw_train.shape, raw_val.shape

((1460, 79), (1459, 79))

In [5]:
# Concatenating two datasets for further pre-process.

features = pd.concat((raw_train, raw_val))  # raw_train (1460 x 79)
features.shape                              # --------
                                            # raw_val (1459 x 79)

(2919, 79)

In [6]:
# Processing numerical columns (mean = 0, standard deviation = 1)

numeric_features = features.dtypes[features.dtypes != 'object'].index
numeric_features

Index(['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces',
       'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold'],
      dtype='object')

In [7]:
features[numeric_features] = features[numeric_features].apply(
    lambda x: (x - x.mean()) / (x.std()))    # function along each column

features.head()

MSSubClass MSZoning  LotFrontage   LotArea Street Alley LotShape  \
0    0.067320       RL    -0.184443 -0.217841   Pave   NaN      Reg   
1   -0.873466       RL     0.458096 -0.072032   Pave   NaN      Reg   
2    0.067320       RL    -0.055935  0.137173   Pave   NaN      IR1   
3    0.302516       RL    -0.398622 -0.078371   Pave   NaN      IR1   
4    0.067320       RL     0.629439  0.518814   Pave   NaN      IR1   

  LandContour Utilities LotConfig  ... ScreenPorch  PoolArea PoolQC Fence  \
0         Lvl    AllPub    Inside  ...   -0.285886 -0.063139    NaN   NaN   
1         Lvl    AllPub       FR2  ...   -0.285886 -0.063139    NaN   NaN   
2         Lvl    AllPub    Inside  ...   -0.285886 -0.063139    NaN   NaN   
3         Lvl    AllPub    Corner  ...   -0.285886 -0.063139    NaN   NaN   
4         Lvl    AllPub       FR2  ...   -0.285886 -0.063139    NaN   NaN   

  MiscFeature   MiscVal    MoSold    YrSold  SaleType  SaleCondition  
0         NaN -0.089577 -1.551918  0.157619        WD         Normal  
1         NaN -0.089577 -0.446848 -0.602858        WD         Normal  
2         NaN -0.089577  1.026577  0.157619        WD         Normal  
3         NaN -0.089577 -1.551918 -1.363335        WD        Abnorml  
4         NaN -0.089577  2.131647  0.157619        WD         Normal  

[5 rows x 79 columns]

In [8]:
# Replacing NAN values with zero is numerical columns.

features[numeric_features] = features[numeric_features].fillna(0)

* `pd.get_dummies(dummy_na=True)`: Add a column to indicate NaNs, if `False` NaNs are ignored.

In [9]:
# Convert categorcial values to discerete numbers

features = pd.get_dummies(features, dummy_na=False)
print(features.shape)

features = pd.get_dummies(features, dummy_na=True)
print(features.shape)

(2919, 288)
(2919, 288)


In [10]:
# Separate training and evaluation data from features.

train_data = features[: raw_train.shape[0]].copy()
train_data[label] = df_train[label].copy()

val_data = features[raw_train.shape[0]:].copy()

train_data.shape, val_data.shape

((1460, 289), (1459, 288))

## Converting the Data to PyTorch Datasets.

* Python `slice()` Function: Returns a slice object.
* `df.values`: Return a Numpy representation of the DataFrame.

In [11]:
import torch

In [12]:
get_tensor = lambda x: torch.tensor(x.values, dtype=torch.float32)

tensors1 = get_tensor(train_data.drop(columns=[label])) # converts the Numpy representation od the data frame to tensors.

type(train_data.values), type(tensors1)

(numpy.ndarray, torch.Tensor)

In [13]:
indices = slice(0, None)

tensors = tuple(a[indices] for a in tensors1)  # this line of code puts each sample (331 features) as an element in a tuple.
indices, type(tensors1), len(tensors1)

(slice(0, None, None), torch.Tensor, 1460)

## Torch Datasets and Torch DataLoader

* The `Dataset` class is an abstract class that is used to define new types of custom datasets.
* The `TensorDataset` is a ready to use class to represent your data as a list of tensors. 

#### Torch Tensor Datasets

`TensorDataset` can be used when we have a list of inputs and a list of outputs (targets). In other words, there is a one-one mapping between input data and the target data (for example an image and its labels).

In [14]:
# Example using TensorDataset Class

inps = torch.arange(1, 16).reshape(5, 3)
outs = torch.randint(1, 3, size=(5,))

ds = torch.utils.data.TensorDataset(inps, outs)
for inp, target in ds:
  print(f'{inp}:{target}')

print('***************************************')

dl = torch.utils.data.DataLoader(ds, batch_size=2, shuffle=True)
for inp, target in dl:
  print(f'{inp}:{target}')


tensor([1, 2, 3]):2
tensor([4, 5, 6]):1
tensor([7, 8, 9]):2
tensor([10, 11, 12]):2
tensor([13, 14, 15]):1
***************************************
tensor([[ 7,  8,  9],
        [13, 14, 15]]):tensor([2, 1])
tensor([[10, 11, 12],
        [ 1,  2,  3]]):tensor([2, 2])
tensor([[4, 5, 6]]):tensor([1])


In [ ]:
tensors = (get_tensor(train_data.drop(columns=[label])),
           torch.log(get_tensor(train_data[label])).reshape((-1,1))) # a tple: fist element: input, second element: labels
print(tensors[0].shape, tensors[1].shape)

a, b = tensors
print(a.shape)
print(b.shape)

for a in tensors:
  print(a)


tensors = tuple(a[indices] for a in tensors)
tensors[0].shape, tensors[1].shape

In [29]:
def get_tensorloader(tensors, indices=slice(0, None)):
  tensors = tuple(a[indices] for a in tensors)
  dataset = torch.utils.data.TensorDataset(*tensors)
  return torch.utils.data.DataLoader(dataset, batch_size=32, shuffle=True)